### ISSUE TITLE
Banda Preprocessing

### ISSUE THREAD

**Issue by sfruf** [sfruf/fMRIAutoregression#1]
Hi @mgxd

I'm Sebastian, a collaborator of Sue's at Northeastern. I'm writing a paper that used BANDA resting state data off of openmind and I'm trying to hunt down the exact preprocessing methods that were used. I used data from /storage/gablab001/banda/data/derivatives/hcp_pipeline, which I was told by Nicole Lo was preprocessed using your HCP scripts. Do you know what steps where used in those scripts? 

Thanks!

**Comment by mgxd** [comment]
Hi @sfruf

I'm unsure if there have been any changes to the outputs since I've left, but my processing included:
Running the BIDSApp wrapper for the HCP Pipelines (v3.26.1). This includes
  - PreFreeSurfer
  - FreeSurfer
  - PostFreeSurfer
  - fMRIVolume
  - fMRISurface
 
I believe this is an example call for one subject.
```
singularity exec -B /storage/gablab001/banda/data:/bids_directory:ro -B /storage/gablab001/banda/data/derivatives/hcp_pipeline:/output -B /storage/gablab001/banda/rawdata/unwarp:/unwarp -B /storage/gablab001/banda/scripts/hcp_pipeline/bids_patch.py:/run2.py -B /tmp:/tmp -C /storage/gablab001/data/singularity-images/test/hcp_pipeline.simg python /run2.py /bids_directory /output participant --participant_label BANDA149 --n_cpus 4 --license_key 'xxxxxx' --coreg 'MSMSulc' --gdcoeffs /unwarp/coeff.grad
```

Then task event files and FSL level 1/2 models were generated. These were used for the `TaskfMRIAnalysis` step. Finally, group contrasts were created using PALM (https://github.com/andersonwinkler/PALM)

I think most of the information can be found in the paper (https://www.sciencedirect.com/science/article/pii/S2213158220300772) starting at section 5.2, but let me know if you have any other questions

**Comment by sfruf** [comment]
Awesome! Thanks @mgxd!
